### ISSUE TITLE
Cannot Connect to device

### ISSUE THREAD

**Issue by benfu12** [MMMZZZZ/Nexus#2]
It says: 

At 921600baud/s... Traceback (most recent call last):.....

raise Exception ("Cannot connect to device.")

**Comment by MMMZZZZ** [comment]
As the warning says in the [main readme](https://github.com/MMMZZZZ/Nexus#description), the script does not work in some cases. I don‘t know why and I currently don‘t have a lot of time to investigate. 

To get a better image of the issue, please let me know the following bits:
* Full response to the `connect` command (either using the Nextion Editor Upload log or a serial montior). 
* Full command line input that you used to initiate the upload
* If possible, the editor version used to compile the TFT file that is currently installed on the devices (NOT the version for the new file you‘re trying to upload). 

Thank you!
Max

**Comment by RuXBee** [comment]
The same exception appear on my script when I try to upload fimware... 

I haved found this source and the part of upload firmware works correctly.
[https://github.com/yozik04/nextion](url)

**Comment by MMMZZZZ** [comment]
@RuXBee Please read my reply right above yours. It states what info I need to even have a chance of fixing it. 

Regards,
Max
